<?php

// !! Generated by: ./vendor/bin/generate-autoload ./src/include.php

spl_autoload_register(function ($class) {
    static $map = array (
  'FailWhale\\Array1' => 'Data.php',
  'FailWhale\\ArrayEntry' => 'Data.php',
  'FailWhale\\Base' => 'Data.php',
  'FailWhale\\DummyClass1' => 'Test.php',
  'FailWhale\\DummyClass2' => 'Test.php',
  'FailWhale\\ErrorException' => 'error helpers.php',
  'FailWhale\\Exception' => 'error helpers.php',
  'FailWhale\\ExceptionImpl' => 'Data.php',
  'FailWhale\\FunctionArg' => 'Data.php',
  'FailWhale\\Globals' => 'Data.php',
  'FailWhale\\Introspection' => 'Introspection.php',
  'FailWhale\\IntrospectionSettings' => 'Introspection.php',
  'FailWhale\\Location' => 'Data.php',
  'FailWhale\\Object1' => 'Data.php',
  'FailWhale\\PrettyPrinter' => 'PrettyPrinter.php',
  'FailWhale\\PrettyPrinterSettings' => 'PrettyPrinter.php',
  'FailWhale\\PrettyPrinterTest' => 'Test.php',
  'FailWhale\\Property' => 'Data.php',
  'FailWhale\\RefCounts' => 'PrettyPrinter.php',
  'FailWhale\\Resource1' => 'Data.php',
  'FailWhale\\Root' => 'Data.php',
  'FailWhale\\Stack' => 'Data.php',
  'FailWhale\\StaticVariable' => 'Data.php',
  'FailWhale\\String1' => 'Data.php',
  'FailWhale\\Text' => 'PrettyPrinter.php',
  'FailWhale\\Type' => 'Data.php',
  'FailWhale\\Value' => 'Value.php',
  'FailWhale\\ValueImpl' => 'Data.php',
  'FailWhale\\Variable' => 'Data.php',
);

    if (isset($map[$class]))
        require_once __DIR__ . "/{$map[$class]}";
}, true, false);

require_once __DIR__ . '/error helpers.php';

