<?php

// !! Generated by: ./vendor/jesseschalken/autoload-generator/bin/generate-autoload src/include.php

spl_autoload_register(function ($class) {
    static $map = array (
  'FailWhale\\Data\\ArrayEntry' => 'Data.php',
  'FailWhale\\Data\\Array_' => 'Data.php',
  'FailWhale\\Data\\Base' => 'Data.php',
  'FailWhale\\Data\\ExceptionData' => 'Data.php',
  'FailWhale\\Data\\Exception_' => 'Data.php',
  'FailWhale\\Data\\FunctionArg' => 'Data.php',
  'FailWhale\\Data\\Globals' => 'Data.php',
  'FailWhale\\Data\\Location' => 'Data.php',
  'FailWhale\\Data\\Object_' => 'Data.php',
  'FailWhale\\Data\\Property' => 'Data.php',
  'FailWhale\\Data\\Resource_' => 'Data.php',
  'FailWhale\\Data\\Root' => 'Data.php',
  'FailWhale\\Data\\Stack' => 'Data.php',
  'FailWhale\\Data\\StaticVariable' => 'Data.php',
  'FailWhale\\Data\\String_' => 'Data.php',
  'FailWhale\\Data\\Type' => 'Data.php',
  'FailWhale\\Data\\Value_' => 'Data.php',
  'FailWhale\\Data\\Variable' => 'Data.php',
  'FailWhale\\ErrorException' => 'error helpers.php',
  'FailWhale\\Exception' => 'error helpers.php',
  'FailWhale\\Introspection' => 'Introspection.php',
  'FailWhale\\IntrospectionSettings' => 'Introspection.php',
  'FailWhale\\PrettyPrinter' => 'PrettyPrinter.php',
  'FailWhale\\PrettyPrinterSettings' => 'PrettyPrinter.php',
  'FailWhale\\RefCounts' => 'PrettyPrinter.php',
  'FailWhale\\Test\\DummyClass1' => 'Test.php',
  'FailWhale\\Test\\DummyClass2' => 'Test.php',
  'FailWhale\\Test\\PrettyPrinterTest' => 'Test.php',
  'FailWhale\\Value' => 'Value.php',
);

    if (isset($map[$class]))
        require_once __DIR__ . "/{$map[$class]}";
}, true, false);

require_once __DIR__ . '/call_js.php';
require_once __DIR__ . '/error helpers.php';
require_once __DIR__ . '/functions.php';

