<?php

// !! Generated by: ./vendor/jesseschalken/autoload-generator/bin/generate-autoload ./src/include.php

spl_autoload_register(function ($class) {
    static $map = array (
  'FailWhale\\Data\\Array1' => 'Data.php',
  'FailWhale\\Data\\ArrayEntry' => 'Data.php',
  'FailWhale\\Data\\Base' => 'Data.php',
  'FailWhale\\Data\\ExceptionImpl' => 'Data.php',
  'FailWhale\\Data\\FunctionArg' => 'Data.php',
  'FailWhale\\Data\\Globals' => 'Data.php',
  'FailWhale\\Data\\Location' => 'Data.php',
  'FailWhale\\Data\\Object1' => 'Data.php',
  'FailWhale\\Data\\Property' => 'Data.php',
  'FailWhale\\Data\\Resource1' => 'Data.php',
  'FailWhale\\Data\\Root' => 'Data.php',
  'FailWhale\\Data\\Stack' => 'Data.php',
  'FailWhale\\Data\\StaticVariable' => 'Data.php',
  'FailWhale\\Data\\String1' => 'Data.php',
  'FailWhale\\Data\\Type' => 'Data.php',
  'FailWhale\\Data\\ValueImpl' => 'Data.php',
  'FailWhale\\Data\\Variable' => 'Data.php',
  'FailWhale\\DummyClass1' => 'Test.php',
  'FailWhale\\DummyClass2' => 'Test.php',
  'FailWhale\\ErrorException' => 'error helpers.php',
  'FailWhale\\Exception' => 'error helpers.php',
  'FailWhale\\Introspection' => 'Introspection.php',
  'FailWhale\\IntrospectionSettings' => 'Introspection.php',
  'FailWhale\\PrettyPrinter' => 'PrettyPrinter.php',
  'FailWhale\\PrettyPrinterSettings' => 'PrettyPrinter.php',
  'FailWhale\\PrettyPrinterTest' => 'Test.php',
  'FailWhale\\RefCounts' => 'PrettyPrinter.php',
  'FailWhale\\Text' => 'PrettyPrinter.php',
  'FailWhale\\Value' => 'Value.php',
);

    if (isset($map[$class]))
        require_once __DIR__ . "/{$map[$class]}";
}, true, false);

require_once __DIR__ . '/error helpers.php';

